# Generated by Django 6.0 on 2026-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_subscriber_is_active_subscriber_last_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerschedule',
            name='send_email',
            field=models.BooleanField(default=False, help_text='Send email notification when this event is created?'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='send_email',
            field=models.BooleanField(default=False, help_text='Send email notification when this event is created?'),
        ),
    ]
