# Generated by Django 6.0 on 2026-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('ramadan', 'Ramadan'), ('taaleem', 'Ta’aleem'), ('sale', 'Lapcoat / Sales')], default='general', max_length=20),
        ),
    ]
