# Generated by Django 6.0 on 2026-04-14 09:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_magazineissue_article_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
