# Generated by Django 6.0 on 2026-04-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_magazineissue_article_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, null=True),
        ),
    ]
