# Generated by Django 6.0 on 2026-09-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_alter_announcement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('zoom', 'Zoom Meeting'), ('google_meet', 'Google Meet'), ('youtube', 'YouTube Live'), ('instagram', 'Instagram Live'), ('facebook', 'Facebook Live'), ('whatsapp', 'WhatsApp Group/Channel'), ('website', 'Website / Registration'), ('pdf', 'PDF Document'), ('drive', 'Google Drive'), ('other', 'Other Link')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Click to join')", max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main link for this announcement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='communications.announcement')),
            ],
            options={
                'ordering': ['-is_primary', 'link_type'],
            },
        ),
    ]
