# Generated by Django 6.0 on 2026-09-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('target_type', models.CharField(choices=[('direct', 'Specific people'), ('offices', 'Specific offices'), ('current', 'All current members'), ('alumni', 'All alumni'), ('everyone', 'Everyone')], max_length=20)),
                ('target_label', models.CharField(blank=True, help_text="Human-readable summary, e.g. 'All alumni'", max_length=200)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='dashboards.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-message__is_pinned', '-message__sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='dashboards__sent_at_48e6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-sent_at'], name='dashboards__sender__05bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecipient',
            index=models.Index(fields=['user', 'is_read', 'is_deleted'], name='dashboards__user_id_ac4d0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'user')},
        ),
    ]
