# Generated by Django 6.0 on 2026-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_email',
            field=models.BooleanField(default=False, help_text='Send email notification when this event is created?'),
        ),
    ]
