# Generated by Django 6.0 on 2026-09-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_layout',
            field=models.CharField(choices=[('overlay', 'Text overlaid on image'), ('separate', 'Image separate from text')], default='overlay', help_text="'Overlay' puts text on the image; 'Separate' shows image above text.", max_length=10),
        ),
    ]
