# Generated by Django 6.0 on 2026-09-16 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namets_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', '📢 Announcement'), ('event', '📅 Event'), ('membership', '🙋 Membership Application'), ('tutor_app', '👨\u200d🏫 Tutor Application'), ('islamiyya', '📖 Islamiyyah Registration'), ('lostfound', '🔍 Lost & Found'), ('qa', '❓ Q&A Question'), ('gallery', '🖼 Gallery'), ('general', 'ℹ General'), ('task', '✅ Task'), ('proposal', '🗳 Proposal'), ('vote', '🗳 Vote cast'), ('nomination', '🕌 Nomination'), ('oath', '🤝 Oath'), ('handover', '🎓 Handover'), ('governance', '🏛 Governance'), ('shop_order', '🛍 Shop Order'), ('booking', '🎟 Booking'), ('free_claim', '🎁 Free Claim'), ('form_purchase', '📄 Form Purchase'), ('equipment', '🔧 Equipment'), ('cbt', '🧠 CBT'), ('resource', '📚 Resource')], default='general', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='namets_noti_recipie_94c0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='namets_noti_created_2646cc_idx'),
        ),
    ]
