services:
  - type: web
    name: namets
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn namets.wsgi:application --workers 4 --log-level info
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        sync: false          # you'll add manually
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: N8N_WEBHOOK_URL
        value: https://n8n-render-5s6o.onrender.com/webhook/namets-events
      - key: WEBHOOK_SECRET
        sync: false