# Generated by Django 6.0 on 2026-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lostfound/')),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='lost', max_length=10)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('watches', 'Watches'), ('caps', 'Caps'), ('accessories', 'Accessories'), ('books', 'Books'), ('other', 'Other')], default='other', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by_name', models.CharField(blank=True, max_length=100)),
                ('claimed_by_contact', models.CharField(blank=True, max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
