# Generated by Django 6.0 on 2026-03-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_applications_open', models.BooleanField(default=False, help_text='Allow tutor applications?')),
                ('membership_applications_open', models.BooleanField(default=False, help_text='Allow membership applications?')),
                ('tutor_intro_text', models.TextField(blank=True, default='Do you aspire to help your brothers and sisters overcome academic challenges? Join us as a tutor!')),
                ('membership_intro_text', models.TextField(blank=True, default='Join NAMETS – work fisabillah, only God can repay. We need dedicated brothers and sisters.')),
            ],
        ),
    ]
