# Generated by Django 6.0 on 2026-03-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
