# Generated by Django 6.0 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_evaluation_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='islamiyya_registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
