# Generated by Django 6.0 on 2026-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_islamiyya_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='islamiyya_whatsapp_link',
            field=models.URLField(blank=True, help_text='Default WhatsApp group link for Islamiyya after verification', null=True),
        ),
    ]
