# Generated by Django 6.0 on 2026-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pendingimportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingimportbatch',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
