# Generated by Django 6.0 on 2026-09-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emaillog_cbt_ai_report_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_ai_report_enabled',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_allow_difficulty_choice',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_allow_retake',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_allow_topic_filter',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_default_question_count',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_default_time_minutes',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_enabled',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_grace_seconds',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_max_questions',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_min_questions',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_pre_test_message',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_pre_test_verse',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_show_answers',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_show_on_public_nav',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='cbt_tab_switch_warning_threshold',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_ai_report_enabled',
            field=models.BooleanField(default=True, help_text='Generate a personalized AI report on the result page (Gemini).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_allow_difficulty_choice',
            field=models.BooleanField(default=True, help_text='Let students pick difficulty (Easy / Medium / Hard / Mixed).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_allow_retake',
            field=models.BooleanField(default=True, help_text="Show a 'Retake Test' button on the result page."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_allow_topic_filter',
            field=models.BooleanField(default=False, help_text='Let students restrict the test to a specific topic.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_default_question_count',
            field=models.PositiveIntegerField(default=20, help_text='Default number of questions when a student starts a test.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_default_time_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Default test duration in minutes.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_enabled',
            field=models.BooleanField(default=False, help_text="Master switch. When OFF, students see 'CBT is currently disabled'."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_grace_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Grace window for late submission (network lag). Not shown to students.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_max_questions',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of questions a student can request.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_min_questions',
            field=models.PositiveIntegerField(default=5, help_text='Minimum number of questions a student can request.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_pre_test_message',
            field=models.TextField(default='This test is for your own benefit. Allah sees your effort — be honest with yourself. Answer sincerely, and may this benefit you.', help_text='Short honesty reminder shown before the test starts.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_pre_test_verse',
            field=models.TextField(default='وَٱللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ\n\n"And Allah knows, while you do not know." — Al-Baqarah 2:216', help_text='Ayah or Hadith shown on the pre-test screen. Keep it short.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_show_answers',
            field=models.BooleanField(default=True, help_text='Show correct answers + explanations on the result page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_show_on_public_nav',
            field=models.BooleanField(default=True, help_text='Show the CBT link in the public Academics navigation.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cbt_tab_switch_warning_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Show the honesty reminder once, after this many tab switches.'),
        ),
    ]
