# Generated by Django 6.0 on 2026-09-16 01:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_emaillog_cbt_ai_report_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('desktop_image', cloudinary.models.CloudinaryField(help_text='Desktop image — 16:9 recommended (1920 × 1080)', max_length=255, verbose_name='desktop_image')),
                ('mobile_image', cloudinary.models.CloudinaryField(help_text='Mobile image — 4:5 recommended (1080 × 1350)', max_length=255, verbose_name='mobile_image')),
                ('cta_text', models.CharField(blank=True, help_text="e.g. 'Learn more', 'Register now'", max_length=60)),
                ('cta_url', models.CharField(blank=True, help_text='e.g. /academics/ or https://…', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide on the homepage carousel.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
