# Generated by Django 6.0 on 2026-09-16 12:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(blank=True, help_text="e.g. 'Learn more'. Leave blank to hide.", max_length=60),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(help_text='Desktop image — 16:9, WebP recommended (1920 × 1080)', upload_to=core.models.hero_desktop_path),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(help_text='Mobile image — 4:5, WebP recommended (1080 × 1350)', upload_to=core.models.hero_mobile_path),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
