# Generated by Django 6.0 on 2026-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_heroslide_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='cta_text',
            field=models.CharField(blank=True, help_text="e.g. 'Learn more'. Leave blank to hide the button.", max_length=60),
        ),
    ]
