# Generated by Django 6.0 on 2026-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_heroslide_cta_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroslide',
            old_name='cta_url',
            new_name='primary_button_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='cta_text',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text',
            field=models.CharField(blank=True, help_text="e.g. 'Learn more'. Leave blank to hide the primary button.", max_length=60),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text',
            field=models.CharField(blank=True, help_text="e.g. 'View events'. Leave blank to hide the secondary button.", max_length=60),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_url',
            field=models.CharField(blank=True, help_text='e.g. /events/ or https://…', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Supporting line under the headline. Leave blank to hide.', max_length=300),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text='Main headline. Leave blank to hide.', max_length=200),
        ),
    ]
