# Generated by Django 6.0 on 2026-02-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='developers/'),
        ),
    ]
