# Generated by Django 6.0 on 2026-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_developer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='email',
            field=models.EmailField(blank=True, help_text='For notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='patron',
            name='receive_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
