# Generated by Django 6.0 on 2026-03-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_patron_email_patron_receive_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Approved for public display'),
        ),
    ]
