# Generated by Django 6.0 on 2026-03-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_developer_photo_alter_executive_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('reg_number', models.CharField(blank=True, help_text='For students', max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('campus_residence', models.BooleanField(default=True)),
                ('islamic_knowledge', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('quran_memorization', models.CharField(choices=[('none', 'None'), ('some', 'Some Surahs'), ('half', 'Half'), ('whole', 'Whole Quran')], max_length=10)),
                ('strong_suit', models.CharField(blank=True, choices=[('public_speaking', 'Public Speaking'), ('tech', 'Tech (Programming, Design)'), ('graphic_design', 'Graphic Design'), ('programming', 'Programming'), ('islamiya_tutor', 'Islamiya Tutor'), ('compassion', 'Compassion/Helping Others'), ('other', 'Other')], help_text='Main strength', max_length=30)),
                ('other_strong_suit', models.CharField(blank=True, help_text='If other, specify', max_length=200)),
                ('how_work_with_people', models.TextField(help_text='How do you work with people?')),
                ('recommendations', models.TextField(help_text='Names of those who can recommend you')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('campus_residence', models.BooleanField(default=True, help_text='Live on campus?')),
                ('strong_courses', models.TextField(help_text='List courses you excel in')),
                ('preferred_course', models.CharField(help_text="Course you'd like to tutor", max_length=200)),
                ('comfort_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='How comfortable are you teaching? (1-5)')),
                ('teaching_skill_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('recommendations', models.TextField(help_text='Names of lecturers, class reps, or others who can recommend you')),
                ('past_experience', models.TextField(blank=True, help_text='Any previous tutoring experience')),
                ('availability', models.TextField(help_text='When are you available?')),
                ('has_materials', models.BooleanField(default=False, help_text='Do you have your own materials?')),
                ('collaborate_on_materials', models.BooleanField(default=False, help_text='Open to collaborating to create standard materials?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Admin has reviewed this application')),
            ],
        ),
    ]
