# Generated by Django 6.0 on 2026-03-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_membershipapplication_tutorapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., President, Secretary, General Inquiry', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='membershipapplication',
            old_name='other_strong_suit',
            new_name='other_skill',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='strong_suit',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select all that apply', to='community.skill'),
        ),
    ]
