# Generated by Django 6.0 on 2026-03-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
