# Generated by Django 6.0 on 2026-04-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_nametsdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='executiveyear',
            name='year_label',
            field=models.CharField(help_text='e.g., 2025/2026', max_length=50),
        ),
    ]
