# Generated by Django 6.0 on 2026-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_patron_slug_alter_executiveyear_year_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
