# Generated by Django 6.0 on 2026-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_patron_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Approved for public display'),
        ),
    ]
