# Generated by Django 6.0 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_alter_question_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='show_on_public',
            field=models.BooleanField(default=False, help_text='Show this executive on the public page (only principal officers).'),
        ),
    ]
