# Generated by Django 6.0 on 2026-09-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_executive_show_on_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='show_on_public',
        ),
    ]
