# Generated by Django 6.0 on 2026-09-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='dashboard_template',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='duties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='office',
            name='icon',
            field=models.CharField(blank=True, default='📋', max_length=50),
        ),
        migrations.AddField(
            model_name='office',
            name='is_custom_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
