# Generated by Django 6.0 on 2026-09-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_office_dashboard_template_office_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='can_manage_all_offices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='head_of_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='office',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.committee'),
        ),
    ]
