# Generated by Django 6.0 on 2026-09-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_committee_office_can_manage_all_offices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
