# Generated by Django 6.0 on 2026-09-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglisting',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Which bank account receives payment for this listing?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_listings', to='business.bankaccount'),
        ),
        migrations.AddField(
            model_name='sellableform',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Which bank account receives payment for this form?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellable_forms', to='business.bankaccount'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Which bank account receives payment for this item?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_items', to='business.bankaccount'),
        ),
    ]
