# Generated by Django 6.0 on 2026-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_bookinglisting_image_alter_equipmentitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('donation', 'Donation'), ('shop_sales', 'Shop Sales'), ('booking_revenue', 'Booking/Ticket Revenue'), ('islamiyya_revenue', 'Islamiyya Registration'), ('form_revenue', 'Form/Registration Revenue'), ('other_income', 'Other Income'), ('equipment', 'Equipment Purchase'), ('event_cost', 'Event Cost'), ('utility', 'Utility Bill'), ('rent', 'Rent'), ('transport', 'Transport'), ('other_expense', 'Other Expense')], max_length=20),
        ),
    ]
