# Generated by Django 6.0 on 2026-09-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_current_session_user_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.PositiveIntegerField()),
                ('department_name', models.CharField(blank=True, max_length=150)),
                ('offices_held', models.JSONField(blank=True, default=list)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('proposals_passed', models.PositiveIntegerField(default=0)),
                ('final_message', models.TextField(blank=True, help_text='Optional message to future EXCO members — stored at handover time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Graduation profile',
                'ordering': ['-graduation_year', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='HandoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ending', models.CharField(blank=True, max_length=50)),
                ('session_starting', models.CharField(blank=True, max_length=50)),
                ('dissolved_count', models.PositiveIntegerField(default=0)),
                ('protected_skipped', models.PositiveIntegerField(default=0, help_text='Active offices skipped because is_protected=True.')),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NominationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated_name', models.CharField(max_length=200)),
                ('nominated_email', models.EmailField(blank=True, max_length=254)),
                ('nominated_phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why is this person being nominated?')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('session_label', models.CharField(blank=True, help_text="Session this is for, e.g. '2025/2026'.", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_made', to=settings.AUTH_USER_MODEL)),
                ('nominated_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations', to='accounts.office')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proposed_budget', models.DecimalField(decimal_places=2, default=0, help_text='Budget in Naira, if any. Leave 0 if not applicable.', max_digits=12)),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('voting', 'Voting Open'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('quorum_percentage', models.PositiveIntegerField(default=60, help_text='Minimum % of eligible voters who must vote for the result to count.')),
                ('approval_percentage', models.PositiveIntegerField(default=50, help_text="Minimum % of cast votes that must be 'Agree' for the proposal to pass.")),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_label', models.CharField(max_length=50, unique=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='When ON, the selection is visible to the outgoing EXCO.')),
                ('snapshot', models.JSONField(blank=True, default=list)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completion_proof', models.FileField(blank=True, help_text='Optional photo or document showing the task was done.', null=True, upload_to='task_proofs/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_office', models.ForeignKey(blank=True, help_text='Assign to an entire office. Leave blank if assigning to a person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.office')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assign to a specific person. Leave blank if assigning to a whole office.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ['status', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree'), ('abstain', 'Abstain')], max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Optional — why did you vote this way?')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cast_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('permission_granted', 'Permission granted'), ('permission_revoked', 'Permission revoked'), ('vote_cast', 'Vote cast'), ('proposal_opened', 'Proposal opened for voting'), ('proposal_closed', 'Proposal closed'), ('handover', 'Handover / dissolve EXCO'), ('payment_logged', 'Payment logged'), ('bulk_import', 'Bulk import'), ('bulk_export', 'Bulk export'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], max_length=32)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Free-form diff or details — e.g. {'before': ..., 'after': ...}")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('office', models.ForeignKey(blank=True, help_text='Office the actor was acting as, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='accounts.office')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='governance__timesta_8b25bc_idx'), models.Index(fields=['office', '-timestamp'], name='governance__office__7e3953_idx'), models.Index(fields=['user', '-timestamp'], name='governance__user_id_f3c732_idx')],
            },
        ),
        migrations.CreateModel(
            name='OathAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_label', models.CharField(max_length=50)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oath_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('user', 'session_label')},
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', '-created_at'], name='governance__status_ee5ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['-voting_end'], name='governance__voting__910934_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='governance__status_26c47b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='governance__assigne_9251ad_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_office', 'status'], name='governance__assigne_640d82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('proposal', 'voter')},
        ),
    ]
