# Generated by Django 6.0 on 2026-09-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Snapshot at graduation time — used for re-onboarding matches.', max_length=254),
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Snapshot at graduation time — used for re-onboarding matches.', max_length=20),
        ),
        migrations.AlterField(
            model_name='graduationprofile',
            name='final_message',
            field=models.TextField(blank=True),
        ),
    ]
