# Generated by Django 6.0 on 2026-09-14 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_graduationprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationprofile',
            options={'ordering': ['-graduation_year', 'user__first_name'], 'verbose_name': 'Graduation profile', 'verbose_name_plural': 'Graduation profiles'},
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='current_location',
            field=models.CharField(blank=True, help_text="e.g. 'Kaduna, Nigeria', 'Toronto, Canada'.", max_length=150),
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='current_occupation',
            field=models.CharField(blank=True, help_text="e.g. 'Software Engineer at XYZ', 'MSc Student at ABU'.", max_length=200),
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional. If blank, initials are used.', null=True, upload_to='alumni_photos/'),
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'linkedin': 'url', 'twitter': '@handle', 'whatsapp': 'number'}"),
        ),
        migrations.AddField(
            model_name='graduationprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='graduationprofile',
            name='department_name',
            field=models.CharField(blank=True, help_text='Snapshot at graduation time.', max_length=150),
        ),
        migrations.AlterField(
            model_name='graduationprofile',
            name='final_message',
            field=models.TextField(blank=True, help_text='A message to future NAMETS members. Shown on your profile.'),
        ),
        migrations.AlterField(
            model_name='graduationprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(db_index=True, help_text='Year they left the EXCO.'),
        ),
        migrations.AlterField(
            model_name='graduationprofile',
            name='offices_held',
            field=models.JSONField(blank=True, default=list, help_text='List of {office, display_label, is_active} dicts, snapshotted at handover.'),
        ),
        migrations.AddIndex(
            model_name='graduationprofile',
            index=models.Index(fields=['graduation_year'], name='governance__graduat_c49056_idx'),
        ),
        migrations.AddIndex(
            model_name='graduationprofile',
            index=models.Index(fields=['-created_at'], name='governance__created_52f458_idx'),
        ),
    ]
