# Generated by Django 6.0 on 2026-09-14 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_alter_graduationprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField(blank=True, help_text='A short note about what this document contains.')),
                ('document_type', models.CharField(choices=[('magazine', 'Session Magazine'), ('report', 'Executive Report'), ('constitution', 'Constitution / Bylaws'), ('minutes', 'Meeting Minutes'), ('photo_album', 'Photo Album'), ('handover', 'Handover Document'), ('other', 'Other')], db_index=True, default='magazine', max_length=20)),
                ('session_label', models.CharField(help_text='e.g. "2023/2024" — shown as the session badge.', max_length=20)),
                ('session_year', models.PositiveIntegerField(db_index=True, help_text='The end year of the session (e.g. 2024 for 2023/2024). Used for sorting.')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover thumbnail (optional, but recommended for the archive grid).', null=True, upload_to='session_docs/covers/')),
                ('external_cover_url', models.URLField(blank=True, help_text='Or paste an external image URL (Google Drive, etc).', max_length=500)),
                ('file', models.FileField(blank=True, help_text='Upload the document. Supported: PDF, PPTX, DOCX, images.', null=True, upload_to='session_docs/files/')),
                ('external_file_url', models.URLField(blank=True, help_text='Or link to the document (Google Drive, Dropbox, etc).', max_length=500)),
                ('external_file_label', models.CharField(blank=True, default='Open document', max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from everyone except uploaders.')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to the top of the archive for emphasis.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the same session.')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session document',
                'verbose_name_plural': 'Session documents',
                'ordering': ['-session_year', 'order', '-uploaded_at'],
                'indexes': [models.Index(fields=['-session_year'], name='governance__session_1e5cf1_idx'), models.Index(fields=['document_type'], name='governance__documen_a15989_idx'), models.Index(fields=['is_published'], name='governance__is_publ_bf25a4_idx')],
            },
        ),
    ]
