# Generated by Django 6.0 on 2026-03-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_tutor_course_tutors_tutorevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('course_name', models.CharField(max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('entry_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('islamiyya', 'Islamiyya')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['entry_type', 'day', 'time_start', 'order'],
            },
        ),
    ]
