# Generated by Django 6.0 on 2026-03-14 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
