# Generated by Django 6.0 on 2026-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_material_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamiyyaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(help_text='Student ID or identification', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('course_focus', models.CharField(choices=[('quran', 'Quran (Tajweed recitation & Memorization)'), ('arabic', 'Arabic Language'), ('tauheed', 'Tauheed'), ('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('seerah', 'Seerah'), ('other', 'Other')], default='quran', max_length=20)),
                ('other_course', models.CharField(blank=True, help_text="If 'Other' selected, specify", max_length=200)),
                ('application_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Payment verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='WhatsApp group link (shown after verification)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="User's enrollment active (if false, they are deleted or expired)")),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
