# Generated by Django 6.0 on 2026-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_islamiyyaregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslamiyyaCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='islamiyyaregistration',
            name='course_focus',
        ),
        migrations.AlterField(
            model_name='islamiyyaregistration',
            name='other_course',
            field=models.CharField(blank=True, help_text='If other, specify', max_length=200),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Select one or more courses', to='academics.islamiyyacourse'),
        ),
    ]
