# Generated by Django 6.0 on 2026-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_islamiyyacourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamiyyaregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
