# Generated by Django 6.0 on 2026-04-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_userresourcesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('participant_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['event_name', 'position'],
            },
        ),
    ]
