# Generated by Django 6.0 on 2026-04-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_competitionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='year',
            field=models.CharField(blank=True, help_text='e.g., 2023/2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Musabaqah 60 Hizb', max_length=100),
        ),
    ]
