# Generated by Django 6.0 on 2026-04-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_competitionresult_is_active_competitionresult_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'ordering': ['event_name', 'category', 'order', 'position'], 'verbose_name_plural': 'Competition Results'},
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within category'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Musabaqah 60 Hizb, Quiz Competition', max_length=100),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='event_name',
            field=models.CharField(help_text='e.g., NAMETS Week 2024', max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='position',
            field=models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place'), ('participant', 'Participant')], default='participant', max_length=50),
        ),
    ]
