# Generated by Django 6.0 on 2026-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_competitionresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='position',
            field=models.CharField(blank=True, default='participant', help_text='e.g 1st, 2nd, 3rd', max_length=50),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='year',
            field=models.CharField(blank=True, help_text='e.g., 2025/2026', max_length=20),
        ),
    ]
