# Generated by Django 6.0 on 2026-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_competitionresult_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresourcesubmission',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
