# Generated by Django 6.0 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_userresourcesubmission_download_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableentry',
            options={'ordering': ['entry_type', 'level', 'day', 'time_start', 'order']},
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='level',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2')], default='level1', help_text='Which level this entry belongs to', max_length=10),
        ),
    ]
