# Generated by Django 6.0 on 2026-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_timetableentry_options_timetableentry_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresourcesubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
