# Generated by Django 6.0 on 2026-09-11 11:14

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_userresourcesubmission_email_sent'),
        ('business', '0004_alter_transaction_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islamiyyaregistration',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='certificate_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamiyya_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('paystack', 'Paystack (Online)'), ('manual', 'Manual (Mosque / Bank Transfer)'), ('cash', 'Cash at Mosque'), ('waived', 'Fee Waived by EXCO')], max_length=20),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('waived', 'Fee Waived')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='refund_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamiyya_refunded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamiyya_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userresourcesubmission',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userresourcesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='islamiyyaregistration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enrollment active flag'),
        ),
        migrations.AlterField(
            model_name='islamiyyaregistration',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('exco_meeting', 'EXCO Meeting'), ('islamiyyah', 'Islamiyyah Class'), ('event', 'Event')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Set for tutorial sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('islamiyya_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.islamiyyaregistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.attendancesession')),
            ],
            options={
                'ordering': ['session', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IslamiyyaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(help_text='e.g., 2025/2026', max_length=20)),
                ('is_open', models.BooleanField(default=False, help_text='Toggle to open/close registration for this session.')),
                ('registration_opens_at', models.DateTimeField(blank=True, help_text='Optional — registration auto-opens at this time.', null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, help_text='Optional — registration auto-closes at this time.', null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed fee every student must pay for this session.', max_digits=10)),
                ('whatsapp_group_link', models.URLField(blank=True, help_text='Shown after payment is verified.', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown on the registration & payment pages.')),
                ('is_active', models.BooleanField(default=True, help_text='Only ONE session can be active. Setting this replaces the previous active one.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Bank account that receives Islamiyya payments for this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamiyya_sessions', to='business.bankaccount')),
            ],
            options={
                'verbose_name': 'Islamiyya Setting',
                'verbose_name_plural': 'Islamiyya Settings',
                'ordering': ['-academic_session'],
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='islamiyya_settings',
            field=models.ForeignKey(blank=True, help_text='Set for Islamiyyah sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.islamiyyasettings'),
        ),
        migrations.AddField(
            model_name='islamiyyaregistration',
            name='session_settings',
            field=models.ForeignKey(blank=True, help_text='Which session this student is registering for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='academics.islamiyyasettings'),
        ),
        migrations.AddIndex(
            model_name='islamiyyaregistration',
            index=models.Index(fields=['payment_status'], name='academics_i_payment_a56d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='islamiyyaregistration',
            index=models.Index(fields=['email'], name='academics_i_email_d7e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='islamiyyaregistration',
            index=models.Index(fields=['application_id'], name='academics_i_applica_62695d_idx'),
        ),
        migrations.AddIndex(
            model_name='islamiyyaregistration',
            index=models.Index(fields=['registration_number'], name='academics_i_registr_e43c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('session', 'user'), name='unique_attendance_per_user_per_session'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('islamiyya_registration__isnull', False)), fields=('session', 'islamiyya_registration'), name='unique_attendance_per_registration_per_session'),
        ),
    ]
