# Generated by Django 6.0 on 2026-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_remove_islamiyyaregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='manual_name',
            field=models.CharField(blank=True, help_text='For manually-added attendees (not linked to a user or registration)', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='manual_role',
            field=models.CharField(blank=True, help_text='e.g. Guest, Imam, External Supervisor', max_length=200),
        ),
    ]
