# Generated by Django 6.0 on 2026-09-13 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_attendancerecord_manual_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shown to students on the CBT setup page.', max_length=200)),
                ('slug', models.SlugField(help_text='Auto-generated from name if left blank.', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the CBT home page.')),
                ('instructions', models.TextField(blank=True, help_text='Optional. Shown above the test for this course only.')),
                ('icon', models.CharField(blank=True, default='📘', help_text='Optional emoji shown next to the course name.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive courses are hidden from students.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('default_question_count', models.PositiveIntegerField(blank=True, help_text='Leave blank to use the global default.', null=True)),
                ('default_time_minutes', models.PositiveIntegerField(blank=True, help_text='Leave blank to use the global default.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbt_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CBT Course',
                'verbose_name_plural': 'CBT Courses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text="Optional. e.g. 'Wudu', 'Salah', 'Tajweed'.", max_length=120)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], help_text='Which of the four options is correct.', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Optional. Shown on the result page when answers are reviewed.')),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('excel', 'Excel import')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions never appear in tests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_answered', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.cbtcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbt_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CBT Question',
                'verbose_name_plural': 'CBT Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'difficulty', 'is_active'], name='academics_q_course__f1cd0e_idx'), models.Index(fields=['course', 'topic'], name='academics_q_course__34cf85_idx')],
            },
        ),
    ]
