# Generated by Django 6.0 on 2026-09-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_cbtcourse_questionbank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome class, e.g. 'fa-book-quran'", max_length=50)),
                ('color', models.CharField(blank=True, default='#0F3D2E', help_text='Hex color for category accent, e.g. #C8A951', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Book category',
                'verbose_name_plural': 'Book categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image (Cloudinary or local storage).', null=True, upload_to='library/covers/')),
                ('external_cover_url', models.URLField(blank=True, help_text='Or paste a hosted image URL (Google Drive, etc).', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of physical copies.')),
                ('shelf_location', models.CharField(blank=True, help_text="e.g. 'Shelf A3', 'Cabinet 2, Row 1'", max_length=80)),
                ('book_format', models.CharField(choices=[('physical', 'Physical only'), ('digital', 'Digital only'), ('both', 'Physical + Digital')], default='physical', max_length=10)),
                ('external_file_url', models.URLField(blank=True, help_text='Link to a digital copy — Google Drive, Dropbox, etc.', max_length=500)),
                ('external_file_label', models.CharField(blank=True, default='Open digital copy', help_text='Text on the download button.', max_length=80)),
                ('is_borrowable', models.BooleanField(default=True, help_text='Uncheck for reference-only books.')),
                ('loan_days', models.PositiveIntegerField(default=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='available', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('borrowed_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Show in the 'Featured' strip on the library home.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='academics.bookcategory')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['status'], name='academics_b_status_8d92df_idx'), models.Index(fields=['-created_at'], name='academics_b_created_d7fb9f_idx'), models.Index(fields=['is_featured'], name='academics_b_is_feat_0fb139_idx'), models.Index(fields=['title'], name='academics_b_title_a0d625_idx')],
            },
        ),
    ]
