# Generated by Django 6.0 on 2026-09-14 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_bookcategory_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='academics_b_status_8d92df_idx',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, help_text='Upload the book (PDF, EPUB, etc).', null=True, upload_to='library/files/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this book from the public library.'),
        ),
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image, or paste an external URL below.', null=True, upload_to='library/covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='external_file_label',
            field=models.CharField(blank=True, default='Download', max_length=80),
        ),
        migrations.AlterField(
            model_name='book',
            name='external_file_url',
            field=models.URLField(blank=True, help_text='Or link to the book (Google Drive, archive.org, etc).', max_length=500),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_published'], name='academics_b_is_publ_c82ac5_idx'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_format',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='current_borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_borrowable',
        ),
        migrations.RemoveField(
            model_name='book',
            name='loan_days',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='shelf_location',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
