# Generated by Django 6.0 on 2026-09-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_alter_book_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.CharField(db_index=True, help_text='Client-generated ID tying multiple violations to one attempt.', max_length=64)),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Switched away from the test tab'), ('fullscreen_exit', 'Exited fullscreen mode'), ('copy_attempt', 'Attempted to copy content'), ('paste_attempt', 'Attempted to paste content'), ('right_click', 'Right-clicked inside the test'), ('devtools', 'Dev tools opened / suspected')], max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context, e.g. question index, time elapsed.')),
                ('triggered_submit', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='academics.cbtcourse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CBT Violation',
                'verbose_name_plural': 'CBT Violations',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['attempt_id', 'occurred_at'], name='academics_c_attempt_cffa93_idx'), models.Index(fields=['-occurred_at'], name='academics_c_occurre_ea70e6_idx'), models.Index(fields=['user', '-occurred_at'], name='academics_c_user_id_b7a87e_idx')],
            },
        ),
    ]
