
"""
Django settings for namets project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import datetime
from logging import config
from logging import config
from pathlib import Path

import ssl

import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()   # loads variables from .env file into environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-kw75-&h1=ms9wuo%g)uaz066)9pi&z844v_5m7q3d&kiu=$&&5'

SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'False'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'admincharts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # my local apps
    'django.contrib.staticfiles',
    'core',
    'communications',
    'events',
    'academics',
    'lostfound',
    'community',
    'gallery',
    'namets_notifications',
    'rest_framework',
    'api',
    'storages', # for django-storages for image cloud buket storage
    'cloudinary_storage',  # cloudinary storage backend for media files
    'cloudinary',
    'ckeditor',         
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'namets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'community.context_processors.developers',
                'community.context_processors.contact_phones',
                'community.context_processors.social_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'namets.wsgi.application'


# Database local sqlite3 for development, inbuilt with django
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""
# uncomment this section and comment the section above to use the neon postgres database in production.
# Replace the DATABASES section of your settings.py with this
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}
"""
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# timezone
TIME_ZONE = 'Africa/Lagos'
USE_TZ = True


# utils/auth.py
from django.conf import settings
from rest_framework.authentication import BaseAuthentication
from rest_framework.exceptions import AuthenticationFailed

class N8NAuthentication(BaseAuthentication):
    def authenticate(self, request):
        token = request.headers.get('X-N8N-Token')
        if not token or token != settings.N8N_API_TOKEN:
            raise AuthenticationFailed('Invalid or missing token')
        return (None, None)  # No user, just authenticated
    
    
# API token for n8n authentication
N8N_API_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDhmZTI0Ny1mYjU2LTQ5NDYtOGQxOS05ZTQ1MmFhY2E0YjIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiYTg4OTkzN2UtNmZiYy00NzZhLThmN2YtNTU2NGI4NWFjOTkwIiwiaWF0IjoxNzc0MzI5NjQxfQ.uhm4T81lzsZ33zXwcJnChH6lV06_jpj6EuYedyhGiko' 


N8N_WEBHOOK_URL='https://namets-n8n.duckdns.org/webhook/namets-events'
WEBHOOK_SECRET = 'qnonxhxlwftbyyqm'

# for hosting on render and allowing render to send requests to our webhook endpoint, we need to allow render's domain in the allowed hosts and csrf trusted origins.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
"""
# for local server and testing do this 
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://*.onrender.com',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
"""

# Clodinary configuration for media file storage
import cloudinary
import cloudinary.uploader
import cloudinary.api


# Cloudinary configuration
cloudinary.config(
    cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key = os.environ.get('CLOUDINARY_API_KEY'),
    api_secret = os.environ.get('CLOUDINARY_API_SECRET'),
    secure = True,  # Force HTTPS for all image URLs [citation:8]
    access_mode='public'
)
CLOUDINARY_STORAGE = {
    'DEFAULT_FOLDER': 'namets',
}

# Tell Django to use Cloudinary for media files in production
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'namets-homepage-cache',
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30 MB limit for file uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30 MB limit for file uploads

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


UNFOLD = {
    "SITE_TITLE": "NAMETS Admin",
    "SITE_HEADER": "NAMETS",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "SITE_ICON": "/static/images/Namets.jpg",
    "LOGIN": {
        "image": "/static/images/Namets.jpg",
    },
    "COPYRIGHT": f"© {datetime.now().year} NAMETS. All rights reserved.",

    "COLORS": {
        "primary": {
            "50":  "232 242 237",
            "100": "209 229 219",
            "200": "163 202 183",
            "300": "118 176 147",
            "400": "72 149 111",
            "500": "26 60 46",
            "600": "22 51 39",
            "700": "18 42 32",
            "800": "14 34 26",
            "900": "10 25 19",
            "950": "6 17 13",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "items": [
                    {
                        "title": _("Overview"),
                        "icon": "dashboard",
                        "link": reverse_lazy("namets_notifications:dashboard"),
                    },
                    {
                        "title": _("Notifications"),
                        "icon": "notifications",
                        "link": reverse_lazy("namets_notifications:inbox"),
                        "badge": "namets_notifications.utils.unread_count_badge",
                    },
                    {
                        "title": _("Activity Log"),
                        "icon": "history",
                        "link": reverse_lazy("namets_notifications:activity"),
                    },
                ],
            },
            {
                "title": _("Communications Team"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Announcements"),
                        "icon": "campaign",
                        "link": reverse_lazy("admin:communications_announcement_changelist"),
                        "permission": lambda request: request.user.has_perm("communications.view_announcement"),
                    },
                    {
                        "title": _("Prayer Times"),
                        "icon": "mosque",
                        "link": reverse_lazy("admin:communications_prayerschedule_changelist"),
                        "permission": lambda request: request.user.has_perm("communications.view_prayerschedule"),
                    },
                    {
                        "title": _("Subscribers"),
                        "icon": "group",
                        "link": reverse_lazy("admin:communications_subscriber_changelist"),
                        "permission": lambda request: request.user.has_perm("communications.view_subscriber"),
                    },
                    {
                        "title": _("Donations"),
                        "icon": "volunteer_activism",
                        "link": reverse_lazy("admin:communications_donationcampaign_changelist"),
                        "permission": lambda request: request.user.has_perm("communications.view_donation"),
                    },
                ],
            },
            {
                "title": _("Events Team"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:events_event_changelist"),
                        "permission": lambda request: request.user.has_perm("events.view_event"),
                    },
                ],
            },
            {
                "title": _("Academics Team"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Courses"),
                        "icon": "school",
                        "link": reverse_lazy("admin:academics_course_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_course"),
                    },
                    {
                        "title": _("Evaluations"),
                        "icon": "grading",
                        "link": reverse_lazy("admin:academics_evaluation_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_evaluation"),
                    },
                    {
                        "title": _("Results"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:academics_result_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_result"),
                    },
                    {
                        "title": _("Timetable"),
                        "icon": "table_view",
                        "link": reverse_lazy("admin:academics_timetableentry_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_timetableentry"),
                    },
                    {
                        "title": _("Islamiyyah"),
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:academics_islamiyyaregistration_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_islamiyyaregistration"),
                    },
                    {
                        "title": _("Tutors"),
                        "icon": "person_raised_hand",
                        "link": reverse_lazy("admin:academics_tutor_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_tutor"),
                    },
                    {
                        "title": _("Resource Submissions"),
                        "icon": "upload_file",
                        "link": reverse_lazy("admin:academics_userresourcesubmission_changelist"),
                        "permission": lambda request: request.user.has_perm("academics.view_userresourcesubmission"),
                    },
                ],
            },
            {
                "title": _("Community Team"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Membership Applications"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy("admin:community_membershipapplication_changelist"),
                        "permission": lambda request: request.user.has_perm("community.view_membershipapplication"),
                    },
                    {
                        "title": _("Tutor Applications"),
                        "icon": "person_add",
                        "link": reverse_lazy("admin:community_tutorapplication_changelist"),
                        "permission": lambda request: request.user.has_perm("community.view_tutorapplication"),
                    },
                    {
                        "title": _("Executives"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:community_executive_changelist"),
                        "permission": lambda request: request.user.has_perm("community.view_executive"),
                    },
                    {
                        "title": _("Patrons"),
                        "icon": "stars",
                        "link": reverse_lazy("admin:community_patron_changelist"),
                        "permission": lambda request: request.user.has_perm("community.view_patron"),
                    },
                    {
                        "title": _("Q&A"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:community_question_changelist"),
                        "permission": lambda request: request.user.has_perm("community.view_question"),
                    },
                ],
            },
            {
                "title": _("Gallery & Lost/Found"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Gallery"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:gallery_gallery_changelist"),
                        "permission": lambda request: request.user.has_perm("gallery.view_gallery"),
                    },
                    {
                        "title": _("Lost & Found"),
                        "icon": "find_in_page",
                        "link": reverse_lazy("admin:lostfound_item_changelist"),
                        "permission": lambda request: request.user.has_perm("lostfound.view_item"),
                    },
                ],
            },
            {
                "title": _("Administration"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Groups & Permissions"),
                        "icon": "lock",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Site Settings"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:core_sitesettings_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}